services:
  proxy:
    image: docker.io/alfresco/alfresco-acs-nginx:${ACS_NGINX_TAG}
    mem_limit: 128m
    environment:
      DISABLE_PROMETHEUS: "true"      
      DISABLE_SYNCSERVICE: "true"
      DISABLE_ADW: "false"
      DISABLE_CONTROL_CENTER: "false"
      ENABLE_CONTENT_APP: "false"
    depends_on:
      alfresco:
        condition: service_healthy
      share:
        condition: service_started
    ports:
      - "8080:8080"
